### ISSUE TITLE
left over LOCKs on system reboot

### ISSUE THREAD

**Issue by BananaAcid** [patrix87/PowerShellGSM#57]
Sometimes my server crashes or a windows update got forced through.

I added a scheduler task to remove all .\servers\*.LOCK files on system start.

Maybe, this could be added by default (when creating the game scheduler task)

**Comment by patrix87** [comment]
Yes, this could prevent some issues.
Please open a PR

**Comment by omayhemo** [comment]
I was flummoxed on why the server wouldn't start.  The cmd window just disappears, you should be pipping output to it and leaving it to keypress for exit, so we can see what's going on.   I'm not sure I understand why the lock management is so messy, perhaps it's because there support for so many different games?

**Comment by patrix87** [comment]
Enable DEBUG mode in the config if you want the window to stay open.
The lock system is there to prevent a state where the server hangs or takes a while to start and then another task start and try to run the server again creating a run away that would impact the performance of the other servers.
