### ISSUE TITLE
Multiple Ark Survival Ascended Servers

### ISSUE THREAD

**Issue by Haidies-AU** [patrix87/PowerShellGSM#82]
I have Ark running all maps from a single install.
I have the Main instance set to do auto backup and update, I have UsePID set to $false.
The main instance wont shutdown any of the others.
Then when it tried to update or start it wont because there are other instances already running.

[Server Log.txt](https://github.com/user-attachments/files/18036242/Server.Log.txt)

**Comment by Haidies-AU** [comment]
This is an on going issue.
Some words of wisdom would be amazing.

**Comment by patrix87** [comment]
I found the issue, the script does not close all instances of an executable, it finds the first one.
It will take some work to fix, I have to add an option to force close all instances if needed.
The issue is that you only want to do that for updates when you run multiple servers from the same install.

**Comment by patrix87** [comment]
After some work I think it is better to avoid running multiple instances from the same folder.
Making this work would involve a lot of work as the script would need to maintain a state of every running instances and lock every scheduled task during an update as well as maintaining backups and proper procedures for each instances.
All of this while keeping compatibility for other games.
